// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPGLO9Tfkudv_xhp6ZV-2X_omNYmGQo-s',
    appId: '1:88687718926:web:8cb9151a16a1c343b8c25f',
    messagingSenderId: '88687718926',
    projectId: 'estacionamentos-fp',
    authDomain: 'estacionamentos-fp.firebaseapp.com',
    storageBucket: 'estacionamentos-fp.appspot.com',
    measurementId: 'G-WH0KBG7L5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA76tf6mQc8PNDNoxvnBfyLlJzMcxUDPlw',
    appId: '1:88687718926:android:271884f7fcb7f846b8c25f',
    messagingSenderId: '88687718926',
    projectId: 'estacionamentos-fp',
    storageBucket: 'estacionamentos-fp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4VPRa8S1WFMuxRyHdnzGCH42hdBYLJI',
    appId: '1:88687718926:ios:530e7533e11b227eb8c25f',
    messagingSenderId: '88687718926',
    projectId: 'estacionamentos-fp',
    storageBucket: 'estacionamentos-fp.appspot.com',
    iosClientId: '88687718926-jdfo71h0fsusgt5b6bakt9qujn2vahtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEstacionamento',
  );
}
